name:           drosophila_visualization
version:        0.0.0
author:         Herman Bergwerf <hermanbergwerf@gmail.com>
description:    WebGL drosophila development
homepage:       https://github.com/hermanbergwerf/fruitfly
environment:
  sdk:          '>=1.8.0 <2.0.0'
dependencies:
  http:         ^0.11.3+13
  glutils:      ^0.0.1
  browser:      ^0.10.0+2
  vector_math:  ^2.0.3
